version: '3.4'

services:
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80"

  foodordering.api:
    container_name: foodordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      -  "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "5005:80"
    